### ISSUE TITLE
Dependencies in CacheFlow aren't always necessarily output -> input

### ISSUE THREAD

**Issue by sgtlambda** [sgtlambda/johnnycache#54]
Example:

```yaml

  - cmd: yarn install
    input:
      - package.json
      - yarn.lock
    output: node_modules

  - cmd: yarn run production
    input:
      - package.json
      - resources/assets
    output:
      - public
```

Proposed solution:

 - Introduce new "dependencies" field where one could define either depended-on files, or commands.
